# Garimpagem de Dados

## Aula 3 - k-Nearest Neighbors

11/10/2017

In [27]:
import numpy as np
from sklearn import datasets

In [28]:
class KNNClassifier(object):
    def __init__(self):
        self.X_train = None
        self.y_train = None

    def euc_distance(self, a, b):
        return np.linalg.norm(a-b)

    def closest(self, row):
        """
        Retorna a classe respondente ao ponto mais próximo do dataset de treino.\
        É um exemplo de implementação do kNN com k=1.
        """
        dists = [self.euc_distance(row, item) for item in self.X_train]
        nei = dists.index(min(dists))
        return self.y_train[nei]

    def fit(self, training_data, training_labels):
        self.X_train = training_data
        self.y_train = training_labels

    def predict(self, to_classify):
        predictions = []
        for row in to_classify:
            label = self.closest(row)
            predictions.append(label)
        return predictions

In [29]:
iris = datasets.load_iris()

In [30]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [31]:
X = iris.data
y = iris.target

In [32]:
print(X)
print(y)
print(X.size)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [35]:
knn = KNNClassifier()

In [36]:
knn.fit(X_train, y_train)

In [37]:
result = knn.predict(X_test)

In [38]:
print(result)

[1, 1, 1, 2, 2, 0, 0, 2, 2, 1, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1, 2, 2]


In [39]:
print(y_test)

[1 1 1 2 2 0 0 2 2 1 1 1 2 1 2 0 2 1 2 2 1 1 1 2 0 1 2 1 0 2 2 2 2 1 0 2 0
 0 1 0 1 0 1 2 2]


In [40]:
from sklearn import metrics

In [41]:
score = metrics.accuracy_score(y_pred=result, y_true=y_test)

In [42]:
print('{0:f}'.format(score))

0.955556


In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
knn1 = KNeighborsClassifier(n_neighbors=1)

In [45]:
knn1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [46]:
result1 = knn1.predict(X_test)

In [47]:
score1 = metrics.accuracy_score(result1, y_test)

In [48]:
print('{0:f}'.format(score1))

0.955556
