# Garimpagem de Dados

## Aula 2 - NumPy

06/10/2017

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

print('')

b = np.array([(1, 2, 3), (4, 5, 6)])
print(b)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [3]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [4]:
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [8]:
b.dot(a)

array([14, 32])

In [5]:
b - a

array([[0, 0, 0],
       [3, 3, 3]])

In [6]:
a**2

array([1, 4, 9])

In [9]:
10*np.sin(a) # seno trigonométrico

array([8.41470985, 9.09297427, 1.41120008])

In [11]:
b<3

array([[ True,  True, False],
       [False, False, False]])

In [16]:
print('Axis 1: %s' % b[0])
print(np.average(b))
print(b.sum())
print(b.min())
print(b.max())

Axis 1: [1 2 3]
3.5
21
1
6


In [19]:
print(b)
b.sum(axis=0) # sum of each column


[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

In [22]:
b.min(axis=1) # min of each row

array([ 6, 15])

In [23]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [31]:
a = np.zeros((3, 5), dtype=np.int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [32]:
np.ones((2,3,4), dtype=np.int16) # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
np.empty([2,3]) # uninitialized, output may vary

array([[6.01433264e+175, 6.93885958e+218, 5.56218858e+180],
       [3.94356143e+180, 1.51978872e-047, 3.14126967e+179]])

In [34]:
c = np.full(5, 2, dtype=np.float)
print(c)

d = np.full((2, 2), 10)
print(d)

[2. 2. 2. 2. 2.]
[[10 10]
 [10 10]]


In [36]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [37]:
np.arange(0, 2, 0.3) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [52]:
c = np.random.rand(2, 3)
print(c)

[[0.6593649  0.34778319 0.53392138]
 [0.70017639 0.56212705 0.77409805]]


In [58]:
c.T


array([[0.6593649 , 0.70017639],
       [0.34778319, 0.56212705],
       [0.53392138, 0.77409805]])

In [42]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [59]:
np.transpose(c)

array([[0.6593649 , 0.70017639],
       [0.34778319, 0.56212705],
       [0.53392138, 0.77409805]])

In [41]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
d[:, 0]

array([1, 4, 7])

In [ ]:
d[:, 1]

In [ ]:
d[:, 0:2]

In [ ]:
d[:, 2]

In [44]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # start:stop:step

In [45]:
np.save('/tmp/x.npy', x)
del(x)
x = np.load('/tmp/x.npy')
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [60]:
# Usar memory mapping quando o conteúdo não couber em memória RAM
x_mm = np.memmap('x_mm.npy', dtype='float32', mode='w+', shape=(1000, 100))
x_mm[999][99] = 12.5
print(x_mm[999][99])

# Delete the memmap instance to close the file (the mmap file is not deleted). 
# Deletion flushes memory changes to disk before removing the object.
del(x_mm)

# Load
x_mm = np.memmap('x_mm.npy', dtype='float32', mode='r', shape=(1000, 100))
print(x_mm[999][99])

12.5
12.5


## Exercícios

1. Como calcular o tamanho da memória usada de qualquer array?
2. Crie a matriz 3x3 com valores em um range de 0 a 8
3. Crie um vetor randômico de tamanho 30 e calcule a média

In [64]:
#1
d = np.arange(1,10)
print(d)
print('%d bytes' % (d.size*d.itemsize))
t = np.zeros((10, 10))
print(t)
print('%d bytes' % (t.size * t.itemsize))

[1 2 3 4 5 6 7 8 9]
72 bytes
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800 bytes


In [71]:
#2
f = np.arange(9)
print(f)
f = np.arange(9).reshape(3,3)
print(f)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [78]:
#3
z = np.random.random(30)

In [79]:
print(z)

print(z.mean())

[5.04356766e-01 7.08257168e-01 5.66728689e-01 5.84126676e-01
 3.72074820e-01 6.39701940e-01 1.92879213e-01 5.49918163e-01
 1.00856198e-01 7.89620949e-01 7.90491094e-01 8.89717829e-01
 6.40196940e-01 2.67808366e-01 2.15923278e-01 6.53634357e-01
 1.05533618e-01 4.04251421e-01 6.41502104e-01 5.56811619e-01
 4.02982056e-01 9.91981122e-01 8.97043472e-01 5.82447104e-01
 6.18694464e-01 2.55475229e-01 2.97918996e-04 3.59734065e-01
 1.87664726e-02 1.15524850e-01]
0.4805779320300984


#### 100 exercícios de NumPy

https://github.com/rougier/numpy-100